# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vald.v1.payload import payload_pb2 as vald_dot_v1_dot_payload_dot_payload__pb2


class MirrorStub(object):
    """Represent the mirror service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/mirror.v1.Mirror/Register',
                request_serializer=vald_dot_v1_dot_payload_dot_payload__pb2.Mirror.Targets.SerializeToString,
                response_deserializer=vald_dot_v1_dot_payload_dot_payload__pb2.Mirror.Targets.FromString,
                _registered_method=True)


class MirrorServicer(object):
    """Represent the mirror service.
    """

    def Register(self, request, context):
        """Register is the RPC to register other mirror servers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MirrorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=vald_dot_v1_dot_payload_dot_payload__pb2.Mirror.Targets.FromString,
                    response_serializer=vald_dot_v1_dot_payload_dot_payload__pb2.Mirror.Targets.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mirror.v1.Mirror', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mirror.v1.Mirror', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mirror(object):
    """Represent the mirror service.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mirror.v1.Mirror/Register',
            vald_dot_v1_dot_payload_dot_payload__pb2.Mirror.Targets.SerializeToString,
            vald_dot_v1_dot_payload_dot_payload__pb2.Mirror.Targets.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
