# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vald/v1/mirror/mirror.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'vald/v1/mirror/mirror.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from vald.v1.payload import payload_pb2 as vald_dot_v1_dot_payload_dot_payload__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bvald/v1/mirror/mirror.proto\x12\tmirror.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1dvald/v1/payload/payload.proto2i\n\x06Mirror\x12_\n\x08Register\x12\x1a.payload.v1.Mirror.Targets\x1a\x1a.payload.v1.Mirror.Targets\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/mirror/register:\x01*BW\n\x1corg.vdaas.vald.api.v1.mirrorB\nValdMirrorP\x01Z)github.com/vdaas/vald/apis/grpc/v1/mirrorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vald.v1.mirror.mirror_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034org.vdaas.vald.api.v1.mirrorB\nValdMirrorP\001Z)github.com/vdaas/vald/apis/grpc/v1/mirror'
  _globals['_MIRROR'].methods_by_name['Register']._loaded_options = None
  _globals['_MIRROR'].methods_by_name['Register']._serialized_options = b'\202\323\344\223\002\025\"\020/mirror/register:\001*'
  _globals['_MIRROR']._serialized_start=103
  _globals['_MIRROR']._serialized_end=208
# @@protoc_insertion_point(module_scope)
