# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vald import payload_pb2 as vald_dot_payload__pb2


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exists = channel.unary_unary(
                '/core.Agent/Exists',
                request_serializer=vald_dot_payload__pb2.Object.ID.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Object.ID.FromString,
                )
        self.Search = channel.unary_unary(
                '/core.Agent/Search',
                request_serializer=vald_dot_payload__pb2.Search.Request.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Search.Response.FromString,
                )
        self.SearchByID = channel.unary_unary(
                '/core.Agent/SearchByID',
                request_serializer=vald_dot_payload__pb2.Search.IDRequest.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Search.Response.FromString,
                )
        self.StreamSearch = channel.stream_stream(
                '/core.Agent/StreamSearch',
                request_serializer=vald_dot_payload__pb2.Search.Request.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Search.Response.FromString,
                )
        self.StreamSearchByID = channel.stream_stream(
                '/core.Agent/StreamSearchByID',
                request_serializer=vald_dot_payload__pb2.Search.IDRequest.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Search.Response.FromString,
                )
        self.Insert = channel.unary_unary(
                '/core.Agent/Insert',
                request_serializer=vald_dot_payload__pb2.Object.Vector.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.StreamInsert = channel.stream_stream(
                '/core.Agent/StreamInsert',
                request_serializer=vald_dot_payload__pb2.Object.Vector.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.MultiInsert = channel.unary_unary(
                '/core.Agent/MultiInsert',
                request_serializer=vald_dot_payload__pb2.Object.Vectors.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.Update = channel.unary_unary(
                '/core.Agent/Update',
                request_serializer=vald_dot_payload__pb2.Object.Vector.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.StreamUpdate = channel.stream_stream(
                '/core.Agent/StreamUpdate',
                request_serializer=vald_dot_payload__pb2.Object.Vector.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.MultiUpdate = channel.unary_unary(
                '/core.Agent/MultiUpdate',
                request_serializer=vald_dot_payload__pb2.Object.Vectors.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.Remove = channel.unary_unary(
                '/core.Agent/Remove',
                request_serializer=vald_dot_payload__pb2.Object.ID.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.StreamRemove = channel.stream_stream(
                '/core.Agent/StreamRemove',
                request_serializer=vald_dot_payload__pb2.Object.ID.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.MultiRemove = channel.unary_unary(
                '/core.Agent/MultiRemove',
                request_serializer=vald_dot_payload__pb2.Object.IDs.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.GetObject = channel.unary_unary(
                '/core.Agent/GetObject',
                request_serializer=vald_dot_payload__pb2.Object.ID.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Object.Vector.FromString,
                )
        self.StreamGetObject = channel.stream_stream(
                '/core.Agent/StreamGetObject',
                request_serializer=vald_dot_payload__pb2.Object.ID.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Object.Vector.FromString,
                )
        self.CreateIndex = channel.unary_unary(
                '/core.Agent/CreateIndex',
                request_serializer=vald_dot_payload__pb2.Control.CreateIndexRequest.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.SaveIndex = channel.unary_unary(
                '/core.Agent/SaveIndex',
                request_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.CreateAndSaveIndex = channel.unary_unary(
                '/core.Agent/CreateAndSaveIndex',
                request_serializer=vald_dot_payload__pb2.Control.CreateIndexRequest.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Empty.FromString,
                )
        self.IndexInfo = channel.unary_unary(
                '/core.Agent/IndexInfo',
                request_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
                response_deserializer=vald_dot_payload__pb2.Info.Index.Count.FromString,
                )


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSearch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSearchByID(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInsert(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiInsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUpdate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRemove(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiRemove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGetObject(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAndSaveIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=vald_dot_payload__pb2.Object.ID.FromString,
                    response_serializer=vald_dot_payload__pb2.Object.ID.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vald_dot_payload__pb2.Search.Request.FromString,
                    response_serializer=vald_dot_payload__pb2.Search.Response.SerializeToString,
            ),
            'SearchByID': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByID,
                    request_deserializer=vald_dot_payload__pb2.Search.IDRequest.FromString,
                    response_serializer=vald_dot_payload__pb2.Search.Response.SerializeToString,
            ),
            'StreamSearch': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSearch,
                    request_deserializer=vald_dot_payload__pb2.Search.Request.FromString,
                    response_serializer=vald_dot_payload__pb2.Search.Response.SerializeToString,
            ),
            'StreamSearchByID': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSearchByID,
                    request_deserializer=vald_dot_payload__pb2.Search.IDRequest.FromString,
                    response_serializer=vald_dot_payload__pb2.Search.Response.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=vald_dot_payload__pb2.Object.Vector.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'StreamInsert': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInsert,
                    request_deserializer=vald_dot_payload__pb2.Object.Vector.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'MultiInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiInsert,
                    request_deserializer=vald_dot_payload__pb2.Object.Vectors.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=vald_dot_payload__pb2.Object.Vector.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'StreamUpdate': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamUpdate,
                    request_deserializer=vald_dot_payload__pb2.Object.Vector.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'MultiUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiUpdate,
                    request_deserializer=vald_dot_payload__pb2.Object.Vectors.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=vald_dot_payload__pb2.Object.ID.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'StreamRemove': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRemove,
                    request_deserializer=vald_dot_payload__pb2.Object.ID.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'MultiRemove': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiRemove,
                    request_deserializer=vald_dot_payload__pb2.Object.IDs.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=vald_dot_payload__pb2.Object.ID.FromString,
                    response_serializer=vald_dot_payload__pb2.Object.Vector.SerializeToString,
            ),
            'StreamGetObject': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamGetObject,
                    request_deserializer=vald_dot_payload__pb2.Object.ID.FromString,
                    response_serializer=vald_dot_payload__pb2.Object.Vector.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=vald_dot_payload__pb2.Control.CreateIndexRequest.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'SaveIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveIndex,
                    request_deserializer=vald_dot_payload__pb2.Empty.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'CreateAndSaveIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAndSaveIndex,
                    request_deserializer=vald_dot_payload__pb2.Control.CreateIndexRequest.FromString,
                    response_serializer=vald_dot_payload__pb2.Empty.SerializeToString,
            ),
            'IndexInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexInfo,
                    request_deserializer=vald_dot_payload__pb2.Empty.FromString,
                    response_serializer=vald_dot_payload__pb2.Info.Index.Count.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.Agent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/Exists',
            vald_dot_payload__pb2.Object.ID.SerializeToString,
            vald_dot_payload__pb2.Object.ID.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/Search',
            vald_dot_payload__pb2.Search.Request.SerializeToString,
            vald_dot_payload__pb2.Search.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/SearchByID',
            vald_dot_payload__pb2.Search.IDRequest.SerializeToString,
            vald_dot_payload__pb2.Search.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamSearch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/core.Agent/StreamSearch',
            vald_dot_payload__pb2.Search.Request.SerializeToString,
            vald_dot_payload__pb2.Search.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamSearchByID(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/core.Agent/StreamSearchByID',
            vald_dot_payload__pb2.Search.IDRequest.SerializeToString,
            vald_dot_payload__pb2.Search.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/Insert',
            vald_dot_payload__pb2.Object.Vector.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamInsert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/core.Agent/StreamInsert',
            vald_dot_payload__pb2.Object.Vector.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MultiInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/MultiInsert',
            vald_dot_payload__pb2.Object.Vectors.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/Update',
            vald_dot_payload__pb2.Object.Vector.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamUpdate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/core.Agent/StreamUpdate',
            vald_dot_payload__pb2.Object.Vector.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MultiUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/MultiUpdate',
            vald_dot_payload__pb2.Object.Vectors.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/Remove',
            vald_dot_payload__pb2.Object.ID.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamRemove(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/core.Agent/StreamRemove',
            vald_dot_payload__pb2.Object.ID.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MultiRemove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/MultiRemove',
            vald_dot_payload__pb2.Object.IDs.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/GetObject',
            vald_dot_payload__pb2.Object.ID.SerializeToString,
            vald_dot_payload__pb2.Object.Vector.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamGetObject(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/core.Agent/StreamGetObject',
            vald_dot_payload__pb2.Object.ID.SerializeToString,
            vald_dot_payload__pb2.Object.Vector.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/CreateIndex',
            vald_dot_payload__pb2.Control.CreateIndexRequest.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/SaveIndex',
            vald_dot_payload__pb2.Empty.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAndSaveIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/CreateAndSaveIndex',
            vald_dot_payload__pb2.Control.CreateIndexRequest.SerializeToString,
            vald_dot_payload__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IndexInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.Agent/IndexInfo',
            vald_dot_payload__pb2.Empty.SerializeToString,
            vald_dot_payload__pb2.Info.Index.Count.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
