# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vald/v1/errors/errors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vald/v1/errors/errors.proto',
  package='errors.v1',
  syntax='proto3',
  serialized_options=b'\n\034org.vdaas.vald.api.v1.errorsB\nValdErrorsP\001Z)github.com/vdaas/vald/apis/grpc/v1/errors',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bvald/v1/errors/errors.proto\x12\terrors.v1\"\x93\x01\n\x06\x45rrors\x1a\x88\x01\n\x03RPC\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x03(\t\x12\x10\n\x08instance\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\x03\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12$\n\x05roots\x18\x07 \x03(\x0b\x32\x15.errors.v1.Errors.RPCBW\n\x1corg.vdaas.vald.api.v1.errorsB\nValdErrorsP\x01Z)github.com/vdaas/vald/apis/grpc/v1/errorsb\x06proto3'
)




_ERRORS_RPC = _descriptor.Descriptor(
  name='RPC',
  full_name='errors.v1.Errors.RPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='errors.v1.Errors.RPC.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='errors.v1.Errors.RPC.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='errors.v1.Errors.RPC.details', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance', full_name='errors.v1.Errors.RPC.instance', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='errors.v1.Errors.RPC.status', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='errors.v1.Errors.RPC.error', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roots', full_name='errors.v1.Errors.RPC.roots', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=190,
)

_ERRORS = _descriptor.Descriptor(
  name='Errors',
  full_name='errors.v1.Errors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ERRORS_RPC, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=190,
)

_ERRORS_RPC.fields_by_name['roots'].message_type = _ERRORS_RPC
_ERRORS_RPC.containing_type = _ERRORS
DESCRIPTOR.message_types_by_name['Errors'] = _ERRORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Errors = _reflection.GeneratedProtocolMessageType('Errors', (_message.Message,), {

  'RPC' : _reflection.GeneratedProtocolMessageType('RPC', (_message.Message,), {
    'DESCRIPTOR' : _ERRORS_RPC,
    '__module__' : 'vald.v1.errors.errors_pb2'
    # @@protoc_insertion_point(class_scope:errors.v1.Errors.RPC)
    })
  ,
  'DESCRIPTOR' : _ERRORS,
  '__module__' : 'vald.v1.errors.errors_pb2'
  # @@protoc_insertion_point(class_scope:errors.v1.Errors)
  })
_sym_db.RegisterMessage(Errors)
_sym_db.RegisterMessage(Errors.RPC)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
