# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vald.v1.payload import payload_pb2 as vald_dot_v1_dot_payload_dot_payload__pb2


class StatsStub(object):
    """Overview
    Represent the resource stats service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResourceStats = channel.unary_unary(
                '/rpc.v1.Stats/ResourceStats',
                request_serializer=vald_dot_v1_dot_payload_dot_payload__pb2.Empty.SerializeToString,
                response_deserializer=vald_dot_v1_dot_payload_dot_payload__pb2.Info.ResourceStats.FromString,
                _registered_method=True)


class StatsServicer(object):
    """Overview
    Represent the resource stats service.
    """

    def ResourceStats(self, request, context):
        """Overview
        Represent the RPC to get the resource stats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResourceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ResourceStats,
                    request_deserializer=vald_dot_v1_dot_payload_dot_payload__pb2.Empty.FromString,
                    response_serializer=vald_dot_v1_dot_payload_dot_payload__pb2.Info.ResourceStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.v1.Stats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc.v1.Stats', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Stats(object):
    """Overview
    Represent the resource stats service.
    """

    @staticmethod
    def ResourceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc.v1.Stats/ResourceStats',
            vald_dot_v1_dot_payload_dot_payload__pb2.Empty.SerializeToString,
            vald_dot_v1_dot_payload_dot_payload__pb2.Info.ResourceStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
