# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vald.v1.payload import payload_pb2 as vald_dot_v1_dot_payload_dot_payload__pb2


class FlushStub(object):
    """Flush service provides ways to flush all indexed vectors.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Flush = channel.unary_unary(
                '/vald.v1.Flush/Flush',
                request_serializer=vald_dot_v1_dot_payload_dot_payload__pb2.Flush.Request.SerializeToString,
                response_deserializer=vald_dot_v1_dot_payload_dot_payload__pb2.Info.Index.Count.FromString,
                _registered_method=True)


class FlushServicer(object):
    """Flush service provides ways to flush all indexed vectors.
    """

    def Flush(self, request, context):
        """A method to flush all indexed vector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlushServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=vald_dot_v1_dot_payload_dot_payload__pb2.Flush.Request.FromString,
                    response_serializer=vald_dot_v1_dot_payload_dot_payload__pb2.Info.Index.Count.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vald.v1.Flush', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vald.v1.Flush', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Flush(object):
    """Flush service provides ways to flush all indexed vectors.
    """

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vald.v1.Flush/Flush',
            vald_dot_v1_dot_payload_dot_payload__pb2.Flush.Request.SerializeToString,
            vald_dot_v1_dot_payload_dot_payload__pb2.Info.Index.Count.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
