# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vald/v1/vald/flush.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from vald.v1.payload import payload_pb2 as vald_dot_v1_dot_payload_dot_payload__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18vald/v1/vald/flush.proto\x12\x07vald.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1dvald/v1/payload/payload.proto2G\n\x05Flush\x12>\n\x05Flush\x12\x19.payload.v1.Flush.Request\x1a\x1c.payload.v1.Info.Index.Count\"\x00\x42R\n\x1aorg.vdaas.vald.api.v1.valdB\tValdFlushP\x01Z\'github.com/vdaas/vald/apis/grpc/v1/valdb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vald.v1.vald.flush_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\032org.vdaas.vald.api.v1.valdB\tValdFlushP\001Z\'github.com/vdaas/vald/apis/grpc/v1/vald'
    _globals['_FLUSH'].methods_by_name['Flush']._options = None
    _globals['_FLUSH'].methods_by_name['Flush']._serialized_options = b'\202\323\344\223\002\006\022\004/flush'
    _globals['_FLUSH']._serialized_start = 99
    _globals['_FLUSH']._serialized_end = 172